{
	'автомобиль': ['auto', 0, ['auto']],
	'дед': ['dedko', 0, ['dedko']],
	'ребенок': ['dieťa', 0, ['dieťa']],
	'дом': ['dom', 0, ['dom']],
	'дома': ['doma', 0, ['doma']],
	'футболист': ['futbalista', 0, ['futbalista']],
	'книга': ['kniha', 0, ['kniha']],
	'кость': ['kosť', 0, ['kosť']],
	'цветок': ['kvet', 0, ['kvet']],
	'аптека': ['lekáreň', 0, ['lekáreň']],
	'кошка': ['mačka', 0, ['mačka']],
	'музей': ['múzeum', 0, ['múzeum']],
	'мужчина': ['muž', 0, ['muž']],
	'площадь': ['námestie', 0, ['námestie']],
	'собака': ['pes', 0, ['pes']],
	'кровать': ['posteľ', 0, ['posteľ']],
	'роза': ['ruža', 0, ['ruža']],
	'сердце': ['srdce', 0, ['srdce']],
	'щенок': ['šteňa', 0, ['šteňa']],
	'женщина': ['žena', 0, ['žena']],
	'высокий': ['vysoký', 0, ['vysoký']],
	'низкий': ['nízky', 0, ['nízky']],
	'большой': ['veľký', 0, ['veľký']],
	'маленький': ['malý', 0, ['malý']],
	'красивый': ['pekný', 0, ['pekný']],
	'прекрасный': ['krásny', 0, ['krásny']],
	'хороший': ['dobrý', 0, ['dobrý']],
	'новый': ['nový', 0, ['nový']],
	'старый': ['starý', 0, ['starý']],
	'современный': ['moderný', 0, ['moderný']],
	'красный': ['červený', 0, ['červený']],
	'зеленый': ['zelený', 0, ['zelený']],
	'чёрный': ['čierny', 0, ['čierny']],
	'белый': ['biely', 0, ['biely']],
	'синий': ['modrý', 0, ['modrý']],
	'жёлтый': ['žltý', 0, ['žltý']],
	'кто': ['kto', 0, ['kto']],
	'что': ['čo', 0, ['čo']],
	'какой, какая, какое': ['aký', 0, ['aký', 'aká', 'aké']],
	'тот, та, то': ['ten', 0, ['ten', 'tá', 'to']],
	'этот, эта, это': ['tento', 0, ['tento', 'táto', 'toto']],
	'какой-нибудь, какая-нибудь, какое-нибудь;\nкакой-то, какая-то, какое-то': ['nejaký', 0, ['nejaký', 'nejaká', 'nejaké']],
	'глагольная связка (есть)': ['je', 0, ['je']],
	'очень': ['veľmi', 0, ['veľmi']],
	'там': ['tam', 0, ['tam']],
	'здесь': ['tu', 0, ['tu']],
	'и': ['a', 0, ['a']],
	'или': ['alebo', 0, ['alebo']],
	'язык': ['jazyk', 0, ['jazyk']],
	'год': ['rok', 0, ['rok']],
	'Словакия': ['slovensko', 0, ['slovensko']],
	'Польша': ['poľsko', 0, ['poľsko']],
	'Германия': ['nemecko', 0, ['nemecko']],
	'Литва': ['litva', 0, ['litva']],
	'Англия': ['anglicko', 0, ['anglicko']],
	'город': ['mesto', 0, ['mesto']],
	'столица': ['hlavné mesto', 0, ['hlavné mesto']],
	'студент, студентка': ['študent', 0, ['študent', 'študentka']],
	'утром': ['ráno', 0, ['ráno']],
	'вечер': ['večer', 0, ['večer']],
	'общежитие': ['internát', 0, ['internát']],
	'письмо': ['list', 0, ['list']],
	'университет': ['univerzita', 0, ['univerzita']],
	'я': ['ja', 0, ['ja']],
	'ты': ['ty', 0, ['ty']],
	'он': ['on', 0, ['on']],
	'она': ['ona', 0, ['ona']],
	'оно': ['ono', 0, ['ono']],
	'мы': ['my', 0, ['my']],
	'вы': ['vy', 0, ['vy']],
	'они': ['oni', 0, ['oni']],
	'они (только женский род)': ['ony', 0, ['ony']],
	'быть': ['byť', 0, ['byť']],
	'жить (где-то)': ['bývať', 0, ['bývať']],
	'зваться, называться': ['volať sa', 0, ['volať sa']],
	'иметь': ['mať', 0, ['mať']],
	'говорить': ['hovoriť', 0, ['hovoriť']],
	'жить, поживать,\nчувствовать себя': ['mať sa', 0, ['mať sa']],
	'читать': ['čítať', 0, ['čítať']],
	'писать': ['písať', 0, ['písať']],
	'причесываться': ['česať sa', 0, ['česať sa']],
	'пить': ['piť', 0, ['piť']],
	'идти': ['ísť', 0, ['ísť']],
	'делать': ['robiť', 0, ['robiť']],
	'привет! пока!': ['ahoj', 0, ['ahoj', 'čau']],
	'доброе утро': ['dobré ráno', 0, ['dobré ráno']],
	'добрый день': ['dobrý deň', 0, ['dobrý deň']],
	'добрый вечер': ['dobrý večer', 0, ['dobrý večer']],
	'до свидания! пока!': ['dovidenia', 0, ['dovidenia', 'dovi']],
	'спокойной ночи': ['dobrú noc', 0, ['dobrú noc']],
	'прощай(те)': ['zbohom', 0, ['zbohom']],
	'Очень приятно.': ['teší ma.', 0, ['teší ma.']],
	'Как дела?': ['ako sa máš?', 0, ['ako sa máš?']],
	'спасибо, благодарю': ['ďakujem', 0, ['ďakujem']],
	'по-словацки': ['po slovensky', 0, ['po slovensky']],
	'по-польски': ['po poľsky', 0, ['po poľsky']],
	'по-немецки': ['po nemecky', 0, ['po nemecky']],
	'по-литовски': ['po litovsky', 0, ['po litovsky']],
	'по-английски': ['po anglicky', 0, ['po anglicky']],
	'как': ['ako', 0, ['ako']],
	'откуда': ['odkiaľ', 0, ['odkiaľ']],
	'где': ['kde', 0, ['kde']],
	'сколько': ['koľko', 0, ['koľko']],
	'который': ['ktorý', 0, ['ktorý']],
	'девятнадцать': ['devätnásť', 0, ['devätnásť']],
	'двадцать': ['dvadsať', 0, ['dvadsať']],
	'двадцать два': ['dvadsaťdva', 0, ['dvadsaťdva']],
	'двадцать три': ['dvadsaťtri', 0, ['dvadsaťtri']],
	'двадцать пять': ['dvadsaťpäť', 0, ['dvadsaťpäť']],
	'хорошо': ['dobre', 0, ['dobre']],
	'плохо': ['zle', 0, ['zle']],
	'также, тоже': ['tiež', 0, ['tiež', 'aj']],
	'да': ['áno', 0, ['áno']],
	'нет': ['nie', 0, ['nie']],
	'другой': ['ostatní', 0, ['ostatní']],
	'немного': ['trochu', 0, ['trochu']],
	'на, в, во': ['na', 0, ['na', 'v', 'vo']],
	'из, от': ['z', 0, ['z', 'zo']],
	'сейчас': ['teraz', 0, ['teraz']],
	'потом, затем': ['potom', 0, ['potom']],
	'семья': ['rodina', 0, ['rodina']],
	'мать': ['mama', 0, ['mama']],
	'отец': ['otec', 0, ['otec']],
	'родители': ['rodičia', 0, ['rodičia']],
	'дочь': ['dcéra', 0, ['dcéra']],
	'сын': ['syn', 0, ['syn']],
	'сестра': ['sestra', 0, ['sestra']],
	'брат': ['brat', 0, ['brat']],
	'братья и сестры': ['súrodenci', 0, ['súrodenci']],
	'бабушка': ['babka', 0, ['babka']],
	'внучка': ['vnučka', 0, ['vnučka']],
	'внук': ['vnuk', 0, ['vnuk']],
	'внуки': ['vnúčatá', 0, ['vnúčatá']],
	'девочка': ['dievča', 0, ['dievča']],
	'мальчик': ['chlapec', 0, ['chlapec']],
	'друг': ['priateľ', 0, ['priateľ']],
	'фотография': ['fotografia', 0, ['fotografia']],
	'имя': ['meno', 0, ['meno']],
	'домашняя работа': ['domáca úloha', 0, ['domáca úloha']],
	'машина; станок': ['stroj', 0, ['stroj']],
	'диван': ['gauč', 0, ['gauč']],
	'улица': ['ulica', 0, ['ulica']],
	'окно': ['okno', 0, ['okno']],
	'кресло': ['kreslo', 0, ['kreslo']],
	'этаж': ['poschodie', 0, ['poschodie']],
	'зверь': ['zviera', 0, ['zviera']],
	'молодой': ['mladý', 0, ['mladý']],
	'умный': ['múdry', 0, ['múdry']],
	'глупый': ['hlúpy', 0, ['hlúpy']],
	'некрасивый': ['škaredý', 0, ['škaredý']],
	'милый': ['milý', 0, ['milý']],
	'чей, чья, чье': ['čí', 0, ['čí', 'čia', 'čie']],
	'мой': ['môj', 0, ['môj']],
	'твой': ['tvoj', 0, ['tvoj']],
	'наш': ['náš', 0, ['náš']],
	'ваш': ['váš', 0, ['váš']],
	'его': ['jeho', 0, ['jeho']],
	'ее': ['jej', 0, ['jej']],
	'их': ['ich', 0, ['ich']],
	'уже': ['už', 0, ['už']],
	'еще': ['ešte', 0, ['ešte']],
	'видеть': ['vidieť', 0, ['vidieť']],
	'один': ['jeden', 0, ['jeden']],
	'два': ['dva', 0, ['dva']],
	'три': ['tri', 0, ['tri']],
	'восемь': ['osem', 0, ['osem']],
	'десять': ['desať', 0, ['desať']],
	'автобус': ['autobus', 0, ['autobus']],
	'велосипед': ['bicykel', 0, ['bicykel']],
	'центр': ['centrum', 0, ['centrum']],
	'время': ['čas', 0, ['čas']],
	'театр': ['divadlo', 0, ['divadlo']],
	'трамвай': ['električka', 0, ['električka']],
	'евро': ['euro', 0, ['euro']],
	'информационный центр': ['infocentrum', 0, ['infocentrum']],
	'юг': ['juh', 0, ['juh']],
	'кофе': ['káva', 0, ['káva']],
	'лошадь, конь': ['kôň', 0, ['kôň']],
	'самолет': ['lietadlo', 0, ['lietadlo']],
	'корабль': ['loď', 0, ['loď']],
	'месяц': ['mesiac', 0, ['mesiac']],
	'метро': ['metro', 0, ['metro']],
	'мотоцикл': ['motorka', 0, ['motorka', 'motocykel']],
	'газетный киоск': ['novinový stánok', 0, ['novinový stánok']],
	'север': ['sever', 0, ['sever']],
	'вокзал': ['stanica', 0, ['stanica']],
	'школа': ['škola', 0, ['škola']],
	'такси': ['taxi', 0, ['taxi', 'taxík']],
	'троллейбус': ['trolejbus', 0, ['trolejbus']],
	'неделя': ['týždeň', 0, ['týždeň']],
	'учитель, учительница': ['učiteľ', 0, ['učiteľ', 'učiteľka']],
	'Вена - в Вену': ['viedeň - do viedne', 0, ['viedeň - do viedne']],
	'выходные': ['víkend', 0, ['víkend']],
	'восток': ['východ', 0, ['východ']],
	'поезд': ['vlak', 0, ['vlak']],
	'запад': ['západ', 0, ['západ']],
	'обменный пункт': ['zmenáreň', 0, ['zmenáreň']],
	'ученик': ['žiak', 0, ['žiak']],
	'полный / студенческий / ученический': ['celý', 0, ['celý', 'študentský', 'žiacky']],
	'в одну сторону / обратный': ['jednosmerný', 0, ['jednosmerný', 'spiatočný']],
	'прошедший': ['minulý', 0, ['minulý']],
	'путешествовать': ['cestovať', 0, ['cestovať']],
	'лететь': ['letieť', 0, ['letieť']],
	'купить': ['kúpiť si', 0, ['kúpiť si']],
	'должен': ['musieť', 0, ['musieť']],
	'желать': ['priať si', 0, ['priať si']],
	'просить': ['prosiť si', 0, ['prosiť si']],
	'понимать': ['rozumieť', 0, ['rozumieť']],
	'стоить': ['stáť', 0, ['stáť']],
	'куда': ['kam', 0, ['kam']],
	'что-то, нечто': ['niečo', 0, ['niečo']],
	'никогда': ['nikdy', 0, ['nikdy']],
	'никакой': ['žiadny', 0, ['žiadny']],
	'четыре': ['štyri', 0, ['štyri']],
	'пять': ['päť', 0, ['päť']],
	'пятьдесят': ['päťdesiat', 0, ['päťdesiat']],
	'мало, немного': ['málo', 0, ['málo']],
	'сначала': ['najskôr', 0, ['najskôr']],
	'наконец, в конце концов': ['nakoniec', 0, ['nakoniec']],
	'пешком': ['pešo', 0, ['pešo']],
	'прямо': ['rovno', 0, ['rovno']],
	'обратно': ['späť', 0, ['späť']],
	'направо': ['vpravo', 0, ['vpravo']],
	'налево': ['vľavo', 0, ['vľavo']],
	'впереди': ['vpredu', 0, ['vpredu']],
	'сзади': ['vzadu', 0, ['vzadu']],
	'к': ['do', 0, ['do']],
	'перед': ['pred', 0, ['pred']],
	'с (со)': ['s', 0, ['s']],
	'над': ['nad', 0, ['nad']],
	'вчера': ['včera', 0, ['včera']],
	'только': ['len', 0, ['len']],
	'пожалуйста (просьба)': ['prosím', 0, ['prosím']],
	'конечно, разумеется': ['samozrejme', 0, ['samozrejme']],
	'Сколько это стоит?': ['koľko to stojí?', 0, ['koľko to stojí?']],
	'Пожалуйста (вот).': ['nech sa páči.', 0, ['nech sa páči.']],
	'Вы понимаете словацкий язык?': ['rozumiete po slovensky?', 0, ['rozumiete po slovensky?']],
	'дуб': ['dub', 0, ['dub']],
	'час': ['hodina', 0, ['hodina']],
	'хлеб': ['chlieb', 0, ['chlieb']],
	'коллега': ['kolega', 0, ['kolega']],
	'обед': ['obed', 0, ['obed']],
	'пицца': ['pizza', 0, ['pizza']],
	'лекция': ['prednáška', 0, ['prednáška']],
	'перемена, перерыв - на перемене, во время перерыва': ['prestávka - cez prestávku', 0, ['prestávka - cez prestávku']],
	'семинар': ['seminár', 0, ['seminár']],
	'одноклассник': ['spolužiak', 0, ['spolužiak']],
	'стол': ['stôl', 0, ['stôl']],
	'дерево': ['strom', 0, ['strom']],
	'туризм': ['turistika', 0, ['turistika']],
	'экскурсия / поход': ['výlet', 0, ['výlet']],
	'тетрадь': ['zošit', 0, ['zošit']],
	'материнский; матери': ['matkin', 0, ['matkin']],
	'отцовский; отца': ['otcov', 0, ['otcov']],
	'охотно, с удовольствием': ['rád', 0, ['rád', 'rada', 'rado']],
	'голодный': ['hladný', 0, ['hladný']],
	'шесть': ['šesť', 0, ['šesť']],
	'семь': ['sedem', 0, ['sedem']],
	'девять': ['deväť', 0, ['deväť']],
	'одиннадцать': ['jedenásť', 0, ['jedenásť']],
	'двенадцать': ['dvanásť', 0, ['dvanásť']],
	'первый': ['prvý', 0, ['prvý']],
	'второй': ['druhý', 0, ['druhý']],
	'третий': ['tretí', 0, ['tretí']],
	'четвертый': ['štvrtý', 0, ['štvrtý']],
	'пятый': ['piaty', 0, ['piaty']],
	'шестой': ['šiesty', 0, ['šiesty']],
	'седьмой': ['siedmy', 0, ['siedmy']],
	'восьмой': ['ôsmy', 0, ['ôsmy']],
	'девятый': ['deviaty', 0, ['deviaty']],
	'десятый': ['desiaty', 0, ['desiaty']],
	'одиннадцатый': ['jedenásty', 0, ['jedenásty']],
	'двенадцатый': ['dvanásty', 0, ['dvanásty']],
	'быть на обеде': ['byť na obede', 0, ['byť na obede']],
	'курить': ['fajčiť', 0, ['fajčiť']],
	'выходить': ['ísť von', 0, ['ísť von']],
	'иметь (иметь обязанность)': ['mať', 0, ['mať']],
	'любить': ['mať rád', 0, ['mať rád']],
	'мочь': ['môcť', 0, ['môcť']],
	'покупать (делать покупки)': ['nakupovať', 0, ['nakupovať']],
	'садиться': ['nastupovať', 0, ['nastupovať']],
	'обедать': ['obedovať', 0, ['obedovať']],
	'одеваться': ['obliekať', 0, ['obliekať']],
	'смотреть телевизор': ['pozerať televíziu', 0, ['pozerať televíziu']],
	'завтракать': ['raňajkovať', 0, ['raňajkovať']],
	'спать': ['spať', 0, ['spať']],
	'учиться': ['učiť sa', 0, ['učiť sa']],
	'умыться': ['umyť', 0, ['umyť']],
	'чистить зубы': ['umyť si zuby', 0, ['umyť si zuby']],
	'знать': ['vedieť', 0, ['vedieť']],
	'вставать': ['vstávať', 0, ['vstávať']],
	'веселиться; развлекаться': ['zabávať sa', 0, ['zabávať sa']],
	'долго': ['dlho', 0, ['dlho']],
	'сегодня': ['dnes', 0, ['dnes']],
	'до обеда': ['doobeda', 0, ['doobeda']],
	'поздно вечером': ['neskoro večer', 0, ['neskoro večer']],
	'после обеда': ['poobede', 0, ['poobede']],
	'досуг; свободное время': ['voľno', 0, ['voľno']],
	'к; в; на': ['k', 0, ['k']],
	'после': ['po', 0, ['po']],
	'от': ['od', 0, ['od']],
	'во время': ['počas', 0, ['počas']],
	'у; за; при': ['pri', 0, ['pri']],
	'Что ты делаешь сегодня вечером?': ['čo robíš dnes večer?', 0, ['čo robíš dnes večer?']],
	'Когда ты утром встаешь?': ['kedy ráno vstávaš?', 0, ['kedy ráno vstávaš?']],
	'блузка': ['blúzka', 0, ['blúzka']],
	'куртка': ['bunda', 0, ['bunda']],
	'шапка': ['čiapka', 0, ['čiapka']],
	'сапоги': ['čižmy', 0, ['čižmy']],
	'магазин хозтоваров': ['drogéria', 0, ['drogéria']],
	'цвет': ['farba', 0, ['farba']],
	'голова': ['hlava', 0, ['hlava']],
	'пальто': ['kabát', 0, ['kabát']],
	'книжный магазин, книжная торговля': ['kníhkupectvo', 0, ['kníhkupectvo']],
	'рубашка': ['košeľa', 0, ['košeľa']],
	'нога': ['noha', 0, ['noha']],
	'брюки': ['nohavice', 0, ['nohavice']],
	'магазин': ['obchod', 0, ['obchod']],
	'одежда': ['oblečenie', 0, ['oblečenie']],
	'картина, рисунок, иллюстрация': ['obraz', 0, ['obraz', 'obrázok']],
	'обувь': ['obuv', 0, ['obuv']],
	'глаз': ['oko', 0, ['oko']],
	'плавки; купальник': ['plavky', 0, ['plavky']],
	'носки': ['ponožky', 0, ['ponožky']],
	'пищевые продукты': ['potraviny', 0, ['potraviny']],
	'пижама': ['pyžamo', 0, ['pyžamo']],
	'джинсы': ['rifle', 0, ['rifle']],
	'рука': ['ruka', 0, ['ruka']],
	'рукавицы': ['rukavice', 0, ['rukavice']],
	'пиджак': ['sako', 0, ['sako']],
	'юбка': ['sukňa', 0, ['sukňa']],
	'свитер': ['sveter', 0, ['sveter']],
	'шарф': ['šál', 0, ['šál']],
	'платье': ['šaty', 0, ['šaty']],
	'текстиль': ['textil', 0, ['textil']],
	'ботинок; туфля': ['topánka', 0, ['topánka']],
	'ботинки; туфли': ['topánky', 0, ['topánky']],
	'майка': ['tričko', 0, ['tričko']],
	'аксессуары': ['doplnok', 0, ['doplnok']],
	'туфли-лодочки': ['lodičky', 0, ['lodičky']],
	'тенниски': ['tenisky', 0, ['tenisky']],
	'ноясок': ['opasok', 0, ['opasok']],
	'сумочка': ['kabelka', 0, ['kabelka']],
	'день рождения': ['narodeniny', 0, ['narodeniny']],
	'элегантный': ['elegantný', 0, ['elegantný']],
	'блондин, блондинка': ['blond', 0, ['blond']],
	'чёрно-белый': ['čierno-biely', 0, ['čierno-biely']],
	'цветной': ['farebný', 0, ['farebný']],
	'фиолетовый': ['fialový', 0, ['fialový']],
	'коричневый': ['hnedý', 0, ['hnedý']],
	'летний': ['letný', 0, ['letný']],
	'любимый': ['obľúbený', 0, ['obľúbený']],
	'оранжевый': ['oranžový', 0, ['oranžový']],
	'одинаковый': ['rovnaký', 0, ['rovnaký']],
	'розовый': ['ružový', 0, ['ružový']],
	'рыжый': ['ryšavý', 0, ['ryšavý']],
	'серый; седой': ['sivý', 0, ['sivý']],
	'поздравлять': ['blahoželať', 0, ['blahoželať']],
	'хотеть': ['chcieť', 0, ['chcieť']],
	'благодарить': ['ďakovať', 0, ['ďakovať']],
	'быть одетым': ['mať oblečené', 0, ['mať oblečené']],
	'носить (одежду, обувь)': ['nosiť', 0, ['nosiť']],
	'обуваться': ['obúvať si', 0, ['obúvať si']],
	'нравиться': ['páčiť sa', 0, ['páčiť sa']],
	'помогать': ['pomáhať', 0, ['pomáhať']],
	'выбрать (себе)': ['vybrať si', 0, ['vybrať si']],
	'примерить; испытать': ['vyskúšať si', 0, ['vyskúšať si']],
	'все': ['všetci', 0, ['všetci']],
	'торговый центр': ['obchodné centrum', 0, ['obchodné centrum']],
	'примерочная кабинка': ['skúšobná kabínka', 0, ['skúšobná kabínka']],
	'Где примерочная кабинка?': ['kde je skúšobná kabínka?', 0, ['kde je skúšobná kabínka?']],
	'Я могу это примерить?': ['môžem si to vyskúšať?', 0, ['môžem si to vyskúšať?']],
	'Это мне (не) нравится': ['to sa mi páči.', 0, ['to sa mi páči.']],
	'дорога': ['cesta', 0, ['cesta']],
	'момент, минута': ['chvíľa', 0, ['chvíľa']],
	'минута': ['minúta', 0, ['minúta']],
	'ручка': ['pero', 0, ['pero']],
	'работа (трудоустройство)': ['práca', 0, ['práca']],
	'расписание': ['rozvrh hodín', 0, ['rozvrh hodín']],
	'секунда': ['sekunda', 0, ['sekunda']],
	'ваза': ['váza', 0, ['váza']],
	'изменение': ['zmena', 0, ['zmena']],
	'идти на работу': ['ísť do práce', 0, ['ísť do práce']],
	'закончиться, кончиться': ['končiť sa', 0, ['končiť sa']],
	'родиться': ['narodiť sa', 0, ['narodiť sa']],
	'считать': ['počítať', 0, ['počítať']],
	'спешить, торопиться': ['ponáhľať sa', 0, ['ponáhľať sa']],
	'равняться': ['rovnať sa', 0, ['rovnať sa']],
	'стать, сделаться': ['stať sa', 0, ['stať sa']],
	'встретиться': ['stretnúť sa', 0, ['stretnúť sa']],
	'длиться, продолжаться': ['trvať', 0, ['trvať']],
	'начинаться': ['začínať sa', 0, ['začínať sa']],
	'мало': ['málo', 0, ['málo']],
	'несколько': ['niekoľko', 0, ['niekoľko']],
	'пара': ['pár', 0, ['pár', 'zopár']],
	'последний': ['posledný', 0, ['posledný']],
	'много': ['veľa', 0, ['veľa']],
	'лучше': ['radšej', 0, ['radšej']],
	'приблизительно; около': ['tak', 0, ['tak']],
	'более, больше': ['viac', 0, ['viac']],
	'прекрасно': ['výborne', 0, ['výborne']],
	'плюс': ['plus', 0, ['plus']],
	'минус': ['mínus', 0, ['mínus']],
	'крат, раз, -жды': ['krát', 0, ['krát']],
	'разделить': ['deleno', 0, ['deleno']],
	'Что случилось?': ['čo sa stalo?', 0, ['čo sa stalo?']],
	'Сколько времени?': ['koľko je hodín?', 0, ['koľko je hodín?']],
	'Сейчас приду': ['prídem o chvíľu.', 0, ['prídem o chvíľu.']],
	'Отлично!': ['to je super.', 0, ['to je super.']],
	'Когда это случилось?': ['kedy sa to stalo?', 0, ['kedy sa to stalo?']],
	'Около десяти': ['okolo desiatej', 0, ['okolo desiatej']],
	'не позже пяти (часов)': ['najneskôr o piatej', 0, ['najneskôr o piatej']],
	'в девять': ['o deviatej', 0, ['o deviatej']],
	'в четверть десятого (пятнадцать минут десятого)': ['o štvrť na desať', 0, ['o štvrť na desať']],
	'в полдесятого': ['o pol desiatej', 0, ['o pol desiatej']],
	'без пятнадцати десять': ['o tri štvrte na desať', 0, ['o tri štvrte na desať']],
	'временная работа': ['brigáda', 0, ['brigáda']],
	'гора': ['hora', 0, ['hora']],
	'календарь': ['kalendár', 0, ['kalendár']],
	'конец': ['koniec', 0, ['koniec']],
	'погода': ['počasie', 0, ['počasie']],
	'каникулы': ['prázdniny', 0, ['prázdniny']],
	'времена года': ['ročné obdobie', 0, ['ročné obdobie']],
	'учебный год': ['ročník', 0, ['ročník']],
	'семестр': ['semester', 0, ['semester']],
	'экзамен': ['skúška', 0, ['skúška']],
	'снег': ['sneh', 0, ['sneh']],
	'вуз': ['vysoká škola', 0, ['vysoká škola']],
	'понедельник': ['pondelok', 0, ['pondelok']],
	'вторник': ['utorok', 0, ['utorok']],
	'среда': ['streda', 0, ['streda']],
	'четверг': ['štvrtok', 0, ['štvrtok']],
	'пятница': ['piatok', 0, ['piatok']],
	'суббота': ['sobota', 0, ['sobota']],
	'воскресенье': ['nedeľa', 0, ['nedeľa']],
	'январь': ['január', 0, ['január']],
	'февраль': ['február', 0, ['február']],
	'март': ['marec', 0, ['marec']],
	'апрель': ['apríl', 0, ['apríl']],
	'май': ['máj', 0, ['máj']],
	'июнь': ['jún', 0, ['jún']],
	'июль': ['júl', 0, ['júl']],
	'август': ['august', 0, ['august']],
	'сентябрь': ['september', 0, ['september']],
	'октябрь': ['október', 0, ['október']],
	'ноябрь': ['november', 0, ['november']],
	'декабрь': ['december', 0, ['december']],
	'весна': ['jar', 0, ['jar']],
	'лето': ['leto', 0, ['leto']],
	'осень': ['jeseň', 0, ['jeseň']],
	'зима': ['zima', 0, ['zima']],
	'горячий': ['horúci', 0, ['horúci']],
	'холодный': ['chladný', 0, ['chladný']],
	'весенний': ['jarný', 0, ['jarný']],
	'осенний': ['jesenný', 0, ['jesenný']],
	'тёплый': ['teplý', 0, ['teplý']],
	'зимний': ['zimný', 0, ['zimný']],
	'купаться': ['kúpať sa', 0, ['kúpať sa']],
	'кататься на лыжах': ['lyžovať sa', 0, ['lyžovať sa']],
	'найти': ['nájsť', 0, ['nájsť']],
	'загорать': ['opaľovať sa', 0, ['opaľovať sa']],
	'просмотреть, осмотреть': ['prezerať si', 0, ['prezerať si']],
	'привыкнуть': ['zvyknúť', 0, ['zvyknúť']],
	'я привык (например, долго спать)': ['zvykol som si', 0, ['zvykol som si']],
	'завтра': ['zajtra', 0, ['zajtra']],
	'куда-то': ['niekam', 0, ['niekam']],
	'где-то': ['niekde', 0, ['niekde']],
	'тогда': ['vtedy', 0, ['vtedy']],
	'всегда': ['vždy', 0, ['vždy']],
	'близко; вблизи; поблизости': ['blízko', 0, ['blízko']],
	'непременно; обязательно': ['určite', 0, ['určite']],
	'наконец': ['konečne', 0, ['konečne']],
	'может быть; возможно': ['možno', 0, ['možno']],
	'опять': ['zase', 0, ['zase']],
	'целый': ['celý', 0, ['celý']],
	'Какой сегодня день?': ['aký je dnes deň?', 0, ['aký je dnes deň?']],
	'летом': ['cez leto', 0, ['cez leto', 'v lete']],
	'на каникулах': ['cez prázdniny', 0, ['cez prázdniny']],
	'Которое сегодня число?': ['koľkého je dnes?', 0, ['koľkého je dnes?']],
	'в вузе': ['na vysokej škole', 0, ['na vysokej škole']],
	'балкон': ['balkón', 0, ['balkón']],
	'будильник': ['budík', 0, ['budík']],
	'квартира': ['byt', 0, ['byt']],
	'жилье; место проживания': ['bývanie', 0, ['bývanie']],
	'холодильник': ['chladnička', 0, ['chladnička']],
	'деревня': ['dedina', 0, ['dedina']],
	'детская комната': ['detská izba', 0, ['detská izba']],
	'детская кроватка': ['detská postieľka', 0, ['detská postieľka']],
	'двери': ['dvere', 0, ['dvere']],
	'гостиница': ['hotel', 0, ['hotel']],
	'коридор': ['chodba', 0, ['chodba']],
	'комната': ['izba', 0, ['izba']],
	'столовая': ['jedáleň', 0, ['jedáleň']],
	'обеденный уголок': ['jedálenský kút', 0, ['jedálenský kút']],
	'ковер': ['koberec', 0, ['koberec']],
	'кухня': ['kuchyňa', 0, ['kuchyňa']],
	'ванная': ['kúpeľňa', 0, ['kúpeľňa']],
	'лампа': ['lampa', 0, ['lampa']],
	'место': ['miesto', 0, ['miesto']],
	'микроволновка': ['mikrovlnka', 0, ['mikrovlnka']],
	'аренда': ['nájom', 0, ['nájom']],
	'объявление': ['nástenka', 0, ['nástenka']],
	'визит; посещение': ['návšteva', 0, ['návšteva']],
	'ночной столик': ['nočný stolík', 0, ['nočný stolík']],
	'гостиная': ['obývačka', 0, ['obývačka']],
	'блочный (многоквартирный) дом': ['panelák', 0, ['panelák']],
	'письменный стол': ['písací stôl', 0, ['písací stôl']],
	'компьютер': ['počítač', 0, ['počítač']],
	'полка': ['polica', 0, ['polica']],
	'частный дом': ['privát', 0, ['privát']],
	'первый этаж': ['prízemie', 0, ['prízemie']],
	'собственный дом; родной дом': ['rodinný dom', 0, ['rodinný dom']],
	'шкаф': ['skriňa', 0, ['skriňa']],
	'спальня': ['spálňa', 0, ['spálňa']],
	'плита': ['sporák', 0, ['sporák']],
	'стул': ['stolička', 0, ['stolička']],
	'телевизор': ['televízor', 0, ['televízor']],
	'туалет': ['toaleta', 0, ['toaleta']],
	'учебник': ['učebnica', 0, ['učebnica']],
	'посудомоечная машина': ['umývačka riadu', 0, ['umývačka riadu']],
	'умывальник': ['umývadlo', 0, ['umývadlo']],
	'ванна': ['vaňa', 0, ['vaňa']],
	'вид': ['výhľad', 0, ['výhľad']],
	'сад; огород': ['záhrada', 0, ['záhrada']],
	'зеркало': ['zrkadlo', 0, ['zrkadlo']],
	'английский': ['angličtina', 0, ['angličtina']],
	'автор': ['autor', 0, ['autor']],
	'официант': ['čašník', 0, ['čašník']],
	'история': ['dejepis', 0, ['dejepis']],
	'эсперантист': ['esperantista', 0, ['esperantista']],
	'эсперанто': ['esperanto', 0, ['esperanto']],
	'фотограф': ['fotograf', 0, ['fotograf']],
	'французский': ['francúzština', 0, ['francúzština']],
	'физика': ['fyzika', 0, ['fyzika']],
	'гимназия': ['gymnázium', 0, ['gymnázium']],
	'хоккеист': ['hokejista', 0, ['hokejista']],
	'герой': ['hrdina', 0, ['hrdina']],
	'Интернет': ['internet', 0, ['internet']],
	'страна': ['krajina', 0, ['krajina']],
	'повар': ['kuchár', 0, ['kuchár']],
	'культура': ['kultúra', 0, ['kultúra']],
	'курс': ['kurz', 0, ['kurz']],
	'врач': ['lekár', 0, ['lekár']],
	'литература': ['literatúra', 0, ['literatúra']],
	'математика': ['matematika', 0, ['matematika']],
	'детский сад, ясли': ['materská škola', 0, ['materská škola', 'škôlka']],
	'специальность': ['odbor', 0, ['odbor']],
	'письменная работа': ['písomka', 0, ['písomka']],
	'полицейский': ['policajt', 0, ['policajt']],
	'польский': ['poľština', 0, ['poľština']],
	'юрист': ['právnik', 0, ['právnik']],
	'продавец': ['predavač', 0, ['predavač']],
	'предмет': ['predmet', 0, ['predmet']],
	'естествознание': ['prírodopis', 0, ['prírodopis']],
	'профессор; перподаватель': ['profesor', 0, ['profesor']],
	'психолог': ['psychológ', 0, ['psychológ']],
	'секретарь': ['sekretár', 0, ['sekretár']],
	'колледж': ['stredná škola', 0, ['stredná škola']],
	'судья': ['sudca', 0, ['sudca']],
	'мир': ['svet', 0, ['svet']],
	'учеба': ['štúdium', 0, ['štúdium']],
	'итальянский': ['taliančina', 0, ['taliančina']],
	'физкультура': ['telesná výchova', 0, ['telesná výchova']],
	'класс, классная комната': ['trieda', 0, ['trieda']],
	'тип': ['typ', 0, ['typ']],
	'география': ['zemepis', 0, ['zemepis']],
	'оценка': ['známka', 0, ['známka']],
	'цена': ['cena', 0, ['cena']],
	'сахар': ['cukor', 0, ['cukor']],
	'чай': ['čaj', 0, ['čaj']],
	'десерт': ['dezert', 0, ['dezert']],
	'сок': ['džús', 0, ['džús']],
	'бутылка': ['fľaša', 0, ['fľaša']],
	'еда': ['jedlo', 0, ['jedlo']],
	'кола': ['kofola', 0, ['kofola']],
	'специя': ['korenie', 0, ['korenie']],
	'ложка': ['lyžička', 0, ['lyžička']],
	'мясо': ['mäso', 0, ['mäso']],
	'мед': ['med', 0, ['med']],
	'минеральная вода': ['minerálka', 0, ['minerálka']],
	'молоко': ['mlieko', 0, ['mlieko']],
	'напиток': ['nápoj', 0, ['nápoj']],
	'нож': ['nôž', 0, ['nôž']],
	'скатерть': ['obrus', 0, ['obrus']],
	'стакан': ['pohár', 0, ['pohár']],
	'суп': ['polievka', 0, ['polievka']],
	'чаевые': ['prepitné', 0, ['prepitné', 'tringelt']],
	'приборы': ['príbor', 0, ['príbor']],
	'приложение': ['príloha', 0, ['príloha']],
	'ресторан': ['reštaurácia', 0, ['reštaurácia']],
	'эскалоп': ['rezeň', 0, ['rezeň']],
	'рыба': ['ryba', 0, ['ryba']],
	'рис': ['ryža', 0, ['ryža']],
	'соль': ['soľ', 0, ['soľ']],
	'свеча': ['sviečka', 0, ['sviečka']],
	'салат': ['šalát', 0, ['šalát']],
	'чашка': ['šálka', 0, ['šálka']],
	'поднос': ['tácňa', 0, ['tácňa']],
	'блюдце': ['tanierik', 0, ['tanierik']],
	'счет': ['účet', 0, ['účet']],
	'ужин': ['večera', 0, ['večera']],
	'вилка': ['vidlička', 0, ['vidlička']],
	'вино': ['víno', 0, ['víno']],
	'овощи': ['zelenina', 0, ['zelenina']],
	'сдача': ['zvyšok', 0, ['zvyšok']],
	'адрес': ['adresa', 0, ['adresa']],
	'айкидо': ['aikido', 0, ['aikido']],
	'бар': ['bar', 0, ['bar']],
	'шторм': ['búrka', 0, ['búrka']],
	'путешествие': ['cestovanie', 0, ['cestovanie']],
	'число': ['číslo', 0, ['číslo']],
	'дождь': ['dážď', 0, ['dážď']],
	'дискотека': ['diskotéka', 0, ['diskotéka']],
	'отпуск, каникулы': ['dovolenka', 0, ['dovolenka']],
	'футбол': ['futbal', 0, ['futbal']],
	'гимнастика': ['gymnastika', 0, ['gymnastika']],
	'туман': ['hmla', 0, ['hmla']],
	'хоккей': ['hokej', 0, ['hokej']],
	'музыка': ['hudba', 0, ['hudba']],
	'кафе': ['kaviareň', 0, ['kaviareň']],
	'кино': ['kino', 0, ['kino']],
	'конь': ['kôň', 0, ['kôň']],
	'аэропорт': ['letisko', 0, ['letisko']],
	'море': ['more', 0, ['more']],
	'почтовая открытка': ['pohľadnica', 0, ['pohľadnica']],
	'прогноз': ['predpoveď', 0, ['predpoveď']],
	'фамилия': ['priezvisko', 0, ['priezvisko']],
	'почтовый индекс': ['psč', 0, ['psč']],
	'спорт': ['šport', 0, ['šport']],
	'теннис': ['tenis', 0, ['tenis']],
	'ветер': ['vietor', 0, ['vietor']],
	'свободное время': ['voľný čas', 0, ['voľný čas']],
	'экскурсия': ['výlet', 0, ['výlet']],
	'увлечение': ['záľuba', 0, ['záľuba']],
	'автомат': ['automat', 0, ['automat']],
	'банк': ['banka', 0, ['banka']],
	'отель, гостиница': ['hotel', 0, ['hotel']],
	'замок': ['hrad', 0, ['hrad']],
	'информация': ['informácie', 0, ['informácie']],
	'книжный магазин': ['kníhkupectvo', 0, ['kníhkupectvo']],
	'контроль': ['kontrola', 0, ['kontrola']],
	'церковь': ['kostol', 0, ['kostol']],
	'луна-парк, парк развлечений': ['lunapark', 0, ['lunapark']],
	'мясная лавка': ['mäsiarstvo', 0, ['mäsiarstvo']],
	'мобильный телефон': ['mobil', 0, ['mobil']],
	'мост': ['most', 0, ['most']],
	'больница': ['nemocnica', 0, ['nemocnica']],
	'житель': ['obyvateľ', 0, ['obyvateľ']],
	'памятник': ['pamiatka', 0, ['pamiatka']],
	'парк': ['park', 0, ['park']],
	'парковка': ['parkovisko', 0, ['parkovisko']],
	'пиццерия': ['pizzeria', 0, ['pizzeria']],
	'поле': ['pole', 0, ['pole']],
	'почта': ['pošta', 0, ['pošta']],
	'бакалея, продукты': ['potraviny', 0, ['potraviny']],
	'река': ['rieka', 0, ['rieka']],
	'сим-карта': ['simkarta', 0, ['simkarta']],
	'киоск': ['trafika', 0, ['trafika']],
	'трактор': ['traktor', 0, ['traktor']],
	'вход': ['vchod', 0, ['vchod']],
	'выход': ['východ', 0, ['východ']],
	'туалет мужской/женский': ['wc muži', 0, ['wc muži', 'ženy']],
	'пункт обмена валюты': ['zmenáreň', 0, ['zmenáreň']],
	'ангина': ['angína', 0, ['angína']],
	'антибиотики': ['antibiotiká', 0, ['antibiotiká']],
	'посылка': ['balík', 0, ['balík']],
	'живот': ['brucho', 0, ['brucho']],
	'грипп': ['chrípka', 0, ['chrípka']],
	'жар': ['horúčka', 0, ['horúčka']],
	'назад': ['chrbát', 0, ['chrbát']],
	'подруга': ['kamarátka', 0, ['kamarátka']],
	'медицина': ['liek', 0, ['liek']],
	'насморк': ['nádcha', 0, ['nádcha']],
	'нос': ['nos', 0, ['nos']],
	'конверт': ['obálka', 0, ['obálka']],
	'фрукты': ['ovocie', 0, ['ovocie']],
	'пациент': ['pacient', 0, ['pacient']],
	'страховой полис': ['preukaz poistenca', 0, ['preukaz poistenca']],
	'проблема': ['problém', 0, ['problém']],
	'палец': ['prst', 0, ['prst']],
	'рецепт': ['recept', 0, ['recept']],
	'Россия': ['rusko', 0, ['rusko']],
	'тело': ['telo', 0, ['telo']],
	'тихо': ['ticho', 0, ['ticho']],
	'ухо': ['ucho', 0, ['ucho']],
	'рот': ['ústa', 0, ['ústa']],
	'витамин': ['vitamín', 0, ['vitamín']],
	'химчистка': ['čistiareň', 0, ['čistiareň']],
	'доллар': ['dolár', 0, ['dolár']],
	'магазин электротоваров': ['elektro', 0, ['elektro']],
	'грамм': ['gram', 0, ['gram']],
	'горшок': ['hrniec', 0, ['hrniec']],
	'килограмм': ['kilo', 0, ['kilo', 'kilogram']],
	'конек, коньки': ['korčuľa', 0, ['korčuľa', 'korčule']],
	'кусок': ['kus', 0, ['kus']],
	'цветочный горшок': ['kvetináč', 0, ['kvetináč']],
	'цветочный магазин': ['kvetinárstvo', 0, ['kvetinárstvo']],
	'фунт': ['libra', 0, ['libra']],
	'литр': ['liter', 0, ['liter']],
	'лыжа, лыжи': ['lyža', 0, ['lyža', 'lyže']],
	'масло': ['maslo', 0, ['maslo']],
	'метр': ['meter', 0, ['meter']],
	'миска': ['miska', 0, ['miska']],
	'мука': ['múka', 0, ['múka']],
	'(банкнота номиналом 50 евро)': ['päťdesiatka', 0, ['päťdesiatka']],
	'деньги': ['peniaze', 0, ['peniaze']],
	'стиральная машина': ['práčka', 0, ['práčka']],
	'рогалик': ['rožok', 0, ['rožok']],
	'шампунь': ['šampón', 0, ['šampón']],
	'яйцо': ['vajíčko', 0, ['vajíčko']],
	'духи': ['voňavka', 0, ['voňavka']],
	'покупатель; заказчик; клиент': ['zákazník', 0, ['zákazník']],
	'доброволец': ['dobrovoľník', 0, ['dobrovoľník']],
	'гербовый сбор': ['kolok', 0, ['kolok']],
	'идея; мысль': ['nápad', 0, ['nápad']],
	'несогласие': ['nesúhlas', 0, ['nesúhlas']],
	'оставаться': ['pobyt', 0, ['pobyt']],
	'разрешение': ['povolenie', 0, ['povolenie']],
	'случай': ['prípad', 0, ['prípad']],
	'согласие': ['súhlas', 0, ['súhlas']],
	'данные': ['údaj', 0, ['údaj']],
	'интерес': ['záujem', 0, ['záujem']],
	'запрос': ['žiadosť', 0, ['žiadosť']],
	'Америка': ['amerika', 0, ['amerika']],
	'е-mail': ['e-mail', 0, ['e-mail']],
	'Индия': ['india', 0, ['india']],
	'Исландия': ['island', 0, ['island']],
	'Япония': ['japonsko', 0, ['japonsko']],
	'комедия': ['komédia', 0, ['komédia']],
	'коммуникация': ['komunikácia', 0, ['komunikácia']],
	'конгресс': ['kongres', 0, ['kongres']],
	'консультация': ['konzultácia', 0, ['konzultácia']],
	'преподавательница': ['lektorka', 0, ['lektorka']],
	'Испания': ['španielsko', 0, ['španielsko']],
	'Италия': ['taliansko', 0, ['taliansko']],
	'телефон': ['telefón', 0, ['telefón']],
	'разговор по телефону': ['telefonovanie', 0, ['telefonovanie']],
	'видео': ['video', 0, ['video']],
	'веб-камера': ['webkamera', 0, ['webkamera']],
	'учительская': ['zborovňa', 0, ['zborovňa']],
	'скидка': ['zľava', 0, ['zľava']],
	'поцелуй': ['bozk', 0, ['bozk']],
	'ворота; подъезд': ['brána', 0, ['brána']],
	'фильм': ['film', 0, ['film']],
	'кивок': ['kývanie', 0, ['kývanie']],
	'объятья': ['objatie', 0, ['objatie']],
	'правда': ['pravda', 0, ['pravda']],
	'свидание': ['rande', 0, ['rande']],
	'развлечение; вечеринка': ['zábava', 0, ['zábava']],
	'машинка': ['autíčko', 0, ['autíčko']],
	'ребеночек; младенчик': ['bábätko', 0, ['bábätko']],
	'кукла': ['bábika', 0, ['bábika']],
	'ребеночек; детка': ['dieťatko', 0, ['dieťatko']],
	'домик': ['domček', 0, ['domček']],
	'кукольный домик': ['domček pre bábiky', 0, ['domček pre bábiky']],
	'игрушка': ['hračka', 0, ['hračka']],
	'игровая площадка': ['ihrisko', 0, ['ihrisko']],
	'комнатка': ['izbička', 0, ['izbička']],
	'кубики': ['kocky', 0, ['kocky']],
	'(детская) коляска': ['kočík', 0, ['kočík']],
	'мамочка': ['mamička', 0, ['mamička']],
	'медвежонок': ['medvedík', 0, ['medvedík']],
	'салочки': ['naháňačka', 0, ['naháňačka']],
	'заголовок; имя; название; наименование': ['názov', 0, ['názov']],
	'беспорядок': ['neporiadok', 0, ['neporiadok']],
	'лото "пары"': ['pexeso', 0, ['pexeso']],
	'кроватка': ['postieľka', 0, ['postieľka']],
	'пазл': ['puzzle', 0, ['puzzle']],
	'посуда; утварь': ['riad', 0, ['riad']],
	'прятки': ['schovávačka', 0, ['schovávačka']],
	'прыгалки': ['skákanie', 0, ['skákanie']],
	'конструктор': ['stavebnica', 0, ['stavebnica']],
	'настольная игра': ['stolová hra', 0, ['stolová hra']],
	'скакалка': ['švihadlo', 0, ['švihadlo']],
	'улочка': ['ulička', 0, ['ulička']],
	'спичка': ['zápalka', 0, ['zápalka']],
	'(авто)авария': ['autonehoda', 0, ['autonehoda']],
	'авторемонтная мастерская': ['autoopravovňa', 0, ['autoopravovňa']],
	'бензин': ['benzín', 0, ['benzín']],
	'человек': ['človek', 0, ['človek']],
	'пешеход': ['chodec', 0, ['chodec']],
	'штраф': ['pokuta', 0, ['pokuta']],
	'полиция': ['polícia', 0, ['polícia']],
	'частичное питание': ['polpenzia', 0, ['polpenzia']],
	'среда; окружающая среда; окружение': ['prostredie', 0, ['prostredie']],
	'сервис': ['servis', 0, ['servis']],
	'шофер': ['šofér', 0, ['šofér']],
	'вождение': ['šoférovanie', 0, ['šoférovanie']],
	'скорая помощь, машина скорой помощи': ['záchranka', 0, ['záchranka']],
	'аквапарк': ['aquapark', 0, ['aquapark']],
	'бассейн': ['kúpalisko', 0, ['kúpalisko']],
	'скука': ['nuda', 0, ['nuda']],
	'отдых': ['oddych', 0, ['oddych']],
	'обстановка; окрестности; окружающая среда; окружение': ['okolie', 0, ['okolie']],
	'порядок': ['poriadok', 0, ['poriadok']],
	'сауна': ['sauna', 0, ['sauna']],
	'снежная баба; снеговик': ['snehuliak', 0, ['snehuliak']],
	'воздушный змей': ['šarkan', 0, ['šarkan']],
	'тур': ['túra', 0, ['túra']],
	'мороженое': ['zmrzlina', 0, ['zmrzlina']],
	'барон': ['barón', 0, ['barón']],
	'бег': ['beh', 0, ['beh']],
	'бегун': ['bežec', 0, ['bežec']],
	'император': ['cisár', 0, ['cisár']],
	'велосипедист': ['cyklista', 0, ['cyklista']],
	'велоспорт': ['cyklistika', 0, ['cyklistika']],
	'статья': ['článok', 0, ['článok']],
	'дан (ступень в боевых искусствах)': ['dan', 0, ['dan']],
	'Греция': ['grécko', 0, ['grécko']],
	'конькобежец': ['korčuliar', 0, ['korčuliar']],
	'катание на коньках': ['korčuľovanie', 0, ['korčuľovanie']],
	'христианин': ['kresťan', 0, ['kresťan']],
	'христианство': ['kresťanstvo', 0, ['kresťanstvo']],
	'легенда': ['legenda', 0, ['legenda']],
	'лыжник': ['lyžiar', 0, ['lyžiar']],
	'лыжный спорт; катание на лыжах': ['lyžovanie', 0, ['lyžovanie']],
	'материал': ['materiál', 0, ['materiál']],
	'медаль': ['medaila', 0, ['medaila']],
	'пояс': ['pás', 0, ['pás']],
	'плавание': ['plávanie', 0, ['plávanie']],
	'пловец': ['plavec', 0, ['plavec']],
	'редактор': ['redaktor', 0, ['redaktor']],
	'семинарская работа': ['seminárka', 0, ['seminárka']],
	'соревнование, состязание': ['súťaž', 0, ['súťaž']],
	'теннисист': ['tenista', 0, ['tenista']],
	'вещь, предмет': ['vec', 0, ['vec']],
	'выступление': ['vystúpenie', 0, ['vystúpenie']],
	'вода': ['voda', 0, ['voda']],
	'волейбол': ['volejbal', 0, ['volejbal']],
	'волейболист': ['volejbalista', 0, ['volejbalista']],
	'Википедия': ['wikipédia', 0, ['wikipédia']],
	'начало': ['začiatok', 0, ['začiatok']],
	'основатель': ['zakladateľ', 0, ['zakladateľ']],
	'борода; подбородок': ['brada', 0, ['brada']],
	'конфета': ['cukrík', 0, ['cukrík']],
	'лодыжка, щиколотка': ['členok', 0, ['členok']],
	'дипломная работа': ['diplomovka', 0, ['diplomovka']],
	'грудь': ['hruď', 0, ['hruď']],
	'груша': ['hruška', 0, ['hruška']],
	'яблоко': ['jablko', 0, ['jablko']],
	'колено': ['koleno', 0, ['koleno']],
	'шея': ['krk', 0, ['krk']],
	'капля': ['kvapka', 0, ['kvapka']],
	'локоть': ['lakeť', 0, ['lakeť']],
	'аптекарь; фармацевт': ['lekárnik', 0, ['lekárnik']],
	'икра; голень': ['lýtko', 0, ['lýtko']],
	'миллилитр': ['mililiter', 0, ['mililiter']],
	'пластырь': ['náplasť', 0, ['náplasť']],
	'бинт; бандаж; повязка': ['obväz', 0, ['obväz']],
	'оса': ['osa', 0, ['osa']],
	'губы': ['pery', 0, ['pery']],
	'профилактика; превенция; предупреждение': ['prevencia', 0, ['prevencia']],
	'совет': ['rada', 0, ['rada']],
	'рука; плечо; часть руки от плеча до локтя': ['rameno', 0, ['rameno']],
	'лестница': ['schody', 0, ['schody']],
	'бедро': ['stehno', 0, ['stehno']],
	'таблетка': ['tabletka', 0, ['tabletka']],
	'зад': ['zadok', 0, ['zadok']],
	'здоровье': ['zdravie', 0, ['zdravie']],
	'дантист, зубной врач': ['zubár', 0, ['zubár']],
	'астрономия': ['astronómia', 0, ['astronómia']],
	'карандаш': ['ceruzka', 0, ['ceruzka']],
	'пассажир': ['cestujúci', 0, ['cestujúci']],
	'мастерская': ['dielňa', 0, ['dielňa']],
	'фирма': ['firma', 0, ['firma']],
	'резинка; ластик': ['guma', 0, ['guma']],
	'химик': ['chemik', 0, ['chemik']],
	'информатик': ['informatik', 0, ['informatik']],
	'информатика': ['informatika', 0, ['informatika']],
	'библиотека': ['knižnica', 0, ['knižnica']],
	'копировальная машина': ['kopírka', 0, ['kopírka']],
	'корзина': ['kôš', 0, ['kôš']],
	'лаборатория': ['laboratórium', 0, ['laboratórium']],
	'менеджер': ['manažér', 0, ['manažér']],
	'менеджмент; управление': ['manažment', 0, ['manažment']],
	'ремонтный рабочий; ремонтник': ['opravár', 0, ['opravár']],
	'бумага': ['papier', 0, ['papier']],
	'пекарь': ['pekár', 0, ['pekár']],
	'пекарня': ['pekáreň', 0, ['pekáreň']],
	'пилот': ['pilot', 0, ['pilot']],
	'плакат': ['plagát', 0, ['plagát']],
	'предприниматель, бизнесмен': ['podnikateľ', 0, ['podnikateľ']],
	'перевод': ['preklad', 0, ['preklad']],
	'переводчик': ['prekladateľ', 0, ['prekladateľ']],
	'перевод; переводческая деятельность': ['prekladateľstvo', 0, ['prekladateľstvo']],
	'проект': ['projekt', 0, ['projekt']],
	'секретарь (ж.р.)': ['sekretárka', 0, ['sekretárka']],
	'суд (учреждение)': ['súd', 0, ['súd']],
	'устный перевод': ['tlmočenie', 0, ['tlmočenie']],
	'педагогика': ['učiteľstvo', 0, ['učiteľstvo']],
	'уборщица': ['upratovačka', 0, ['upratovačka']],
	'учреждение': ['úrad', 0, ['úrad']],
	'работник, сотрудник': ['zamestnanec', 0, ['zamestnanec']],
	'розетка': ['zásuvka', 0, ['zásuvka']],
	'программное обеспечение; приложение': ['aplikácia', 0, ['aplikácia']],
	'точка; пункт; очко': ['bod', 0, ['bod']],
	'CD/DVD-привод': ['cd', 0, ['cd', 'dvd mechanika']],
	'часть': ['časť', 0, ['časť']],
	'пароль': ['heslo', 0, ['heslo']],
	'икона': ['ikona', 0, ['ikona']],
	'кабель': ['kábel', 0, ['kábel']],
	'калькулятор': ['kalkulačka', 0, ['kalkulačka']],
	'клавиша': ['kláves', 0, ['kláves']],
	'клавиатура': ['klávesnica', 0, ['klávesnica']],
	'колесико': ['koliesko', 0, ['koliesko']],
	'черепаха': ['korytnačka', 0, ['korytnačka']],
	'рисование': ['kreslenie', 0, ['kreslenie']],
	'меню': ['menu', 0, ['menu']],
	'монитор': ['monitor', 0, ['monitor']],
	'мышь': ['myš', 0, ['myš']],
	'ноутбук': ['notebook', 0, ['notebook']],
	'панель': ['panel', 0, ['panel']],
	'экран': ['plátno', 0, ['plátno']],
	'половина': ['polovica', 0, ['polovica']],
	'использование': ['používanie', 0, ['používanie']],
	'презентация': ['prezentácia', 0, ['prezentácia']],
	'папка (фолдер)': ['priečinok', 0, ['priečinok']],
	'команда': ['príkaz', 0, ['príkaz']],
	'программа': ['program', 0, ['program']],
	'динамик': ['reproduktor', 0, ['reproduktor']],
	'программное обеспечение': ['softvér', 0, ['softvér']],
	'файл': ['súbor', 0, ['súbor']],
	'текст': ['text', 0, ['text']],
	'принтер': ['tlačiareň', 0, ['tlačiareň']],
	'кнопка, главиша': ['tlačidlo', 0, ['tlačidlo']],
	'поиск': ['vyhľadávanie', 0, ['vyhľadávanie']],
	'состав, конфигурация': ['zostava', 0, ['zostava']],
	'часы': ['hodinky', 0, ['hodinky']],
	'концентрация': ['koncentrácia', 0, ['koncentrácia']],
	'кроссворд': ['krížovka', 0, ['krížovka']],
	'мозг': ['mozog', 0, ['mozog']],
	'память': ['pamäť', 0, ['pamäť']],
	'потоп': ['potopa', 0, ['potopa']],
	'сон': ['spánok', 0, ['spánok']],
	'система': ['systém', 0, ['systém']],
	'темнота': ['tma', 0, ['tma']],
	'училище': ['učilište', 0, ['učilište']],
	'стихотворение': ['báseň', 0, ['báseň']],
	'художественная литература': ['beletria', 0, ['beletria']],
	'брошюра': ['brožúrka', 0, ['brožúrka']],
	'журнал': ['časopis', 0, ['časopis']],
	'шоколад': ['čokoláda', 0, ['čokoláda']],
	'произведение': ['dielo', 0, ['dielo']],
	'документ': ['dokument', 0, ['dokument']],
	'драма': ['dráma', 0, ['dráma']],
	'эпос': ['epika', 0, ['epika']],
	'гость': ['hosť', 0, ['hosť']],
	'каталог': ['katalóg', 0, ['katalóg']],
	'лирика': ['lyrika', 0, ['lyrika']],
	'супруг': ['manžel', 0, ['manžel']],
	'супруга': ['manželka', 0, ['manželka']],
	'газета': ['noviny', 0, ['noviny']],
	'прогулка': ['prechádzka', 0, ['prechádzka']],
	'психология': ['psychológia', 0, ['psychológia']],
	'богач': ['boháč', 0, ['boháč']],
	'дух': ['duch', 0, ['duch']],
	'галерея': ['galéria', 0, ['galéria']],
	'крепость; замок': ['hrad', 0, ['hrad']],
	'хозяин замка': ['hradný pán', 0, ['hradný pán']],
	'камень': ['kameň', 0, ['kameň']],
	'керамика': ['keramika', 0, ['keramika']],
	'король': ['kráľ', 0, ['kráľ']],
	'скупец': ['lakomec', 0, ['lakomec']],
	'лес': ['les', 0, ['les']],
	'стена': ['múr', 0, ['múr']],
	'двор': ['nádvorie', 0, ['nádvorie']],
	'горная страна; горы': ['pohorie', 0, ['pohorie']],
	'принц': ['princ', 0, ['princ']],
	'скала': ['skala', 0, ['skala']],
	'старуха': ['starena', 0, ['starena']],
	'колодец': ['studňa', 0, ['studňa']],
	'святой': ['svätec', 0, ['svätec']],
	'дворянин': ['šľachtic', 0, ['šľachtic']],
	'трон': ['trón', 0, ['trón']],
	'башня': ['veža', 0, ['veža']],
	'властелин; правитель': ['vládca', 0, ['vládca']],
	'солдат; воин': ['vojak', 0, ['vojak']],
	'армия': ['vojsko', 0, ['vojsko']],
	'выставка': ['výstava', 0, ['výstava']],
	'возникновение': ['vznik', 0, ['vznik']],
	'замок; дворец': ['zámok', 0, ['zámok']],
	'коллекция; собрание': ['zbierka', 0, ['zbierka']],
	'оружие': ['zbraň', 0, ['zbraň']],
	'поздравление': ['blahoželanie', 0, ['blahoželanie']],
	'ведьма': ['bosorka', 0, ['bosorka']],
	'подарок': ['darček', 0, ['darček']],
	'щи': ['kapustnica', 0, ['kapustnica']],
	'пирог': ['koláč', 0, ['koláč']],
	'рождественская песня; колядка': ['koleda', 0, ['koleda']],
	'облатка; вафля': ['oblátka', 0, ['oblátka']],
	'месса; церковная служба': ['omša', 0, ['omša']],
	'грецкий орех': ['orech', 0, ['orech']],
	'украшение': ['ozdoba', 0, ['ozdoba']],
	'полночь': ['polnoc', 0, ['polnoc']],
	'роса': ['rosa', 0, ['rosa']],
	'лента': ['stužka', 0, ['stužka']],
	'праздник': ['sviatok', 0, ['sviatok']],
	'ивовая ветка-хлесталка': ['šibačka', 0, ['šibačka']],
	'сочельник': ['štedrý deň', 0, ['štedrý deň']],
	'традиция': ['tradícia', 0, ['tradícia']],
	'Пасха': ['veľká noc', 0, ['veľká noc']],
	'Рождество': ['vianoce', 0, ['vianoce']],
	'зайчик': ['zajačik', 0, ['zajačik']],
	'обычай': ['zvyk', 0, ['zvyk']],
	'Чехия': ['česko', 0, ['česko']],
	'член': ['člen', 0, ['člen']],
	'двойной крест': ['dvojkríž', 0, ['dvojkríž']],
	'Европейский союз': ['európska únia', 0, ['európska únia']],
	'граница': ['hranica', 0, ['hranica']],
	'юго-запад': ['juhozápad', 0, ['juhozápad']],
	'княжество': ['kniežatstvo', 0, ['kniežatstvo']],
	'Венгрия': ['maďarsko', 0, ['maďarsko']],
	'Моравия': ['morava', 0, ['morava']],
	'посетитель': ['návštevník', 0, ['návštevník']],
	'область': ['oblasť', 0, ['oblasť']],
	'фон': ['pozadie', 0, ['pozadie']],
	'полоса; лента; дорожка': ['pruh', 0, ['pruh']],
	'Австрия': ['rakúsko', 0, ['rakúsko']],
	'Славянин': ['slovan', 0, ['slovan']],
	'Словацкая Республика': ['slovenská republika', 0, ['slovenská republika']],
	'государство': ['štát', 0, ['štát']],
	'холм (гора) с тремя вершинами': ['trojvršie', 0, ['trojvršie']],
	'Украина': ['ukrajina', 0, ['ukrajina']],
	'Великая Моравия': ['veľká morava', 0, ['veľká morava']],
	'флаг': ['vlajka', 0, ['vlajka']],
	'герб': ['znak', 0, ['znak']],
	'басня': ['bájka', 0, ['bájka']],
	'цель': ['cieľ', 0, ['cieľ']],
	'сорт; вид': ['druh', 0, ['druh']],
	'бутылка; банка': ['fľaša', 0, ['fľaša']],
	'гнездо': ['hniezdo', 0, ['hniezdo']],
	'озерко': ['jazierko', 0, ['jazierko']],
	'ветвь, ветка': ['konár', 0, ['konár']],
	'контейнер': ['kontajner', 0, ['kontajner']],
	'корова': ['krava', 0, ['krava']],
	'медведь': ['medveď', 0, ['medveď']],
	'морковь': ['mrkva', 0, ['mrkva']],
	'мусор': ['odpadky', 0, ['odpadky']],
	'организация': ['organizácia', 0, ['organizácia']],
	'орел': ['orol', 0, ['orol']],
	'помидор': ['paradajka', 0, ['paradajka']],
	'петрушка': ['petržlen', 0, ['petržlen']],
	'эдельвейс': ['plesnivec', 0, ['plesnivec']],
	'сон-трава': ['poniklec', 0, ['poniklec']],
	'пища; питание; еда': ['potrava', 0, ['potrava']],
	'природа': ['príroda', 0, ['príroda']],
	'первоцвет': ['prvosienka', 0, ['prvosienka']],
	'странник, путник': ['pútnik', 0, ['pútnik']],
	'растение': ['rastlina', 0, ['rastlina']],
	'курица': ['sliepka', 0, ['sliepka']],
	'известия, новости': ['správy', 0, ['správy']],
	'сурок': ['svišť', 0, ['svišť']],
	'тень': ['tieň', 0, ['tieň']],
	'улей': ['úľ', 0, ['úľ']],
	'пчела': ['včela', 0, ['včela']],
	'выдра': ['vydra', 0, ['vydra']],
	'заяц': ['zajac', 0, ['zajac']],
	'колокольчик; звонок': ['zvonček', 0, ['zvonček']],
	'двоюродный брат': ['bratranec', 0, ['bratranec']],
	'двоюродная сестра': ['sesternica', 0, ['sesternica']],
	'Племянник': ['synovec', 0, ['synovec']],
	'племянница': ['neter', 0, ['neter']],
	'свекор': ['svokor', 0, ['svokor']],
	'свекровь': ['svokra', 0, ['svokra']],
	'зять': ['zať', 0, ['zať']],
	'невеста': ['nevesta', 0, ['nevesta']],
	'шурин': ['švagor', 0, ['švagor']],
	'золовка': ['švagriná', 0, ['švagriná']],
	'вдовец': ['vdovec', 0, ['vdovec']],
	'вдова': ['vdova', 0, ['vdova']],
	'потомок': ['potomok', 0, ['potomok']],
	'единственный ребенок': ['jedináčik', 0, ['jedináčik']],
	'предложение': ['ponuka', 0, ['ponuka']],
	'тур; экскурсия': ['zájazd', 0, ['zájazd']],
	'катание на лыжах': ['lyžovačka', 0, ['lyžovačka']],
	'мегаполис; столица': ['metropola', 0, ['metropola']],
	'любитель': ['milovník', 0, ['milovník']],
	'состояние': ['podmienka', 0, ['podmienka']],
	'стрелка; указатель': ['šípka', 0, ['šípka']],
	'диета': ['strava', 0, ['strava']],
	'размещение; проживание': ['ubytovanie', 0, ['ubytovanie']],
	'игровая комната': ['herňa', 0, ['herňa']],
	'дополнительная кровать': ['prístelka', 0, ['prístelka']],
	'плата; оплата': ['poplatok', 0, ['poplatok']],
	'полупансион': ['polpenzia', 0, ['polpenzia']],
	'подъемник': ['vlek', 0, ['vlek']],
	'фуникулер; канатная дорога': ['lanovka', 0, ['lanovka']],
	'горнолыжный склон': ['zjazdovka', 0, ['zjazdovka']],
	'период; сезон': ['obdobie', 0, ['obdobie']],
	'возможность': ['možnosť', 0, ['možnosť']],
	'делегат': ['delegát', 0, ['delegát']],
	'аниматор': ['animátor', 0, ['animátor']],
	'полотенце': ['osuška', 0, ['osuška']],
	'круиз': ['plavba', 0, ['plavba']],
	'участник': ['účastník', 0, ['účastník']],
	'гид': ['sprievodca', 0, ['sprievodca']],
	'авиабилет': ['letenka', 0, ['letenka']],
	'полет': ['let', 0, ['let']],
	'поездка': ['jazda', 0, ['jazda']],
	'бак': ['nádrž', 0, ['nádrž']],
	'маршрут': ['trasa ž)', 0, ['trasa ž)']],
	'участок': ['úsek', 0, ['úsek']],
	'трасса': ['trať', 0, ['trať']],
	'вагон': ['vozeň', 0, ['vozeň']],
	'территория': ['územie', 0, ['územie']],
	'опыт': ['zážitok', 0, ['zážitok']],
	'остров': ['ostrov', 0, ['ostrov']],
	'пригород': ['predmestie', 0, ['predmestie']],
	'ветеран': ['veterán', 0, ['veterán']],
	'мачете': ['mačeta', 0, ['mačeta']],
	'бета-каротин': ['betakarotén', 0, ['betakarotén']],
	'боль': ['bolesť', 0, ['bolesť']],
	'генетика': ['genetika', 0, ['genetika']],
	'потеря веса': ['chudnutie', 0, ['chudnutie']],
	'иммунитет': ['imunita', 0, ['imunita']],
	'недостаток': ['nedostatok', 0, ['nedostatok']],
	'оптимизм': ['optimizmus', 0, ['optimizmus']],
	'организм': ['organizmus', 0, ['organizmus']],
	'промышленность': ['priemysel', 0, ['priemysel']],
	'сироп': ['sirup', 0, ['sirup']],
	'наука': ['veda', 0, ['veda']],
	'акция': ['akcia', 0, ['akcia']],
	'жилье; размещение; проживание': ['bývanie', 0, ['bývanie']],
	'развлекательный центр': ['zábavné centrum', 0, ['zábavné centrum']],
	'магазин с косметическими и бытовыми товарами': ['drogéria', 0, ['drogéria']],
	'электроника': ['elektronika', 0, ['elektronika']],
	'фитнес-центр': ['fitnescentrum', 0, ['fitnescentrum']],
	'магазин игрушек': ['hračkárstvo', 0, ['hračkárstvo']],
	'гипермаркет': ['hypermarket', 0, ['hypermarket']],
	'парикмахерская': ['kaderníctvo', 0, ['kaderníctvo']],
	'карточка; карта': ['karta', 0, ['karta']],
	'платежная карта': ['platobná karta', 0, ['platobná karta']],
	'ювелирный магазин': ['klenotníctvo', 0, ['klenotníctvo']],
	'покупка': ['kúpa', 0, ['kúpa']],
	'угол': ['kútik', 0, ['kútik']],
	'детский уголок': ['detský kútik', 0, ['detský kútik']],
	'крайний срок': ['lehota', 0, ['lehota']],
	'мода': ['móda', 0, ['móda']],
	'женская мода': ['dámska móda', 0, ['dámska móda']],
	'мужская мода': ['pánska móda', 0, ['pánska móda']],
	'множество; количество': ['množstvo', 0, ['množstvo']],
	'традиционный магазин': ['kamenný', 0, ['kamenný', 'klasický obchod']],
	'виртуальный (интернет)магазин': ['virtuálny', 0, ['virtuálny', 'internetový obchod']],
	'заказ': ['objednávka', 0, ['objednávka']],
	'оптика': ['optika', 0, ['optika']],
	'канцелярские товары': ['papiernictvo', 0, ['papiernictvo']],
	'оплата': ['platba', 0, ['platba']],
	'мошенник': ['podvodník', 0, ['podvodník']],
	'спортзал': ['posilňovňa', 0, ['posilňovňa']],
	'еда; продукты питания': ['potraviny', 0, ['potraviny']],
	'предметы первой необходимости': ['potreby', 0, ['potreby']],
	'товары для животных; зоомагазин': ['chovateľské potreby', 0, ['chovateľské potreby']],
	'магазин спорттоваров': ['športové potreby', 0, ['športové potreby']],
	'продажа': ['predaj', 0, ['predaj']],
	'опрос': ['prieskum', 0, ['prieskum']],
	'продукт': ['produkt', 0, ['produkt']],
	'реклама': ['reklama', 0, ['reklama']],
	'жалоба; рекламация': ['reklamácia', 0, ['reklamácia']],
	'самообслуживание': ['samoobsluha', 0, ['samoobsluha']],
	'услуга': ['služba', 0, ['služba']],
	'подарочные и упаковочные услуги': ['služba darčeková a baliaca', 0, ['služba darčeková a baliaca']],
	'финансовые услуги': ['služba finančná', 0, ['služba finančná']],
	'ассортимент': ['sortiment', 0, ['sortiment']],
	'стенд': ['stánok', 0, ['stánok']],
	'встреча': ['stretnutie', 0, ['stretnutie']],
	'супермаркет': ['supermarket', 0, ['supermarket']],
	'табак': ['tabak', 0, ['tabak']],
	'товары': ['tovar', 0, ['tovar']],
	'подарочные товары': ['darčekový tovar', 0, ['darčekový tovar']],
	'табачный киоск': ['trafika', 0, ['trafika']],
	'тележка': ['vozík', 0, ['vozík']],
	'выбор': ['výber', 0, ['výber']],
	'преимущество': ['výhoda', 0, ['výhoda']],
	'распродажа': ['výpredaj', 0, ['výpredaj']],
	'клиент': ['zákazník', 0, ['zákazník']],
	'гарантия': ['záruka', 0, ['záruka']],
	'привычка': ['zvyk', 0, ['zvyk']],
}
